---
# Elasticsearch - Minimal single-node configuration for 4-core constraint
# Official docs: https://github.com/elastic/helm-charts/tree/main/elasticsearch
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/instance: elasticsearch
    app.kubernetes.io/part-of: platform
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: elasticsearch
      version: '8.5.1'  # Use stable 8.x version
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Single node for minimal footprint
    replicas: 1
    minimumMasterNodes: 1
    
    # Relaxed health check for single node
    clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
    
    # Minimal JVM heap for 4-core constraint
    esJavaOpts: "-Xmx256m -Xms256m"
    
    # Minimal resource allocation
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    
    # Small persistent volume
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
    
    # Disable security for dev (enable in prod)
    # Official recommendation: Use security.enabled=false only for non-production
    # Docs: https://github.com/elastic/helm-charts/blob/main/elasticsearch/README.md#security
    extraEnvs:
      - name: xpack.security.enabled
        value: "false"
      - name: discovery.type
        value: "single-node"
---
# Kibana - Minimal configuration
# Official docs: https://github.com/elastic/helm-charts/tree/main/kibana
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kibana
  namespace: logging
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/instance: kibana
    app.kubernetes.io/part-of: platform
spec:
  interval: 10m
  timeout: 10m
  dependsOn:
    - name: elasticsearch
      namespace: logging
  chart:
    spec:
      chart: kibana
      version: '8.5.1'
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Minimal resources
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi
    
    # Connect to Elasticsearch without security
    elasticsearchHosts: "http://elasticsearch-master:9200"
    
    # Disable health checks that require authentication
    healthCheckPath: "/app/kibana"
---
# Fluent Bit - Lightweight log forwarder
# Official docs: https://docs.fluentbit.io/manual/installation/kubernetes
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/part-of: platform
spec:
  interval: 10m
  chart:
    spec:
      chart: fluent-bit
      version: '0.21.7'
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: false
  values:
    # Minimal resources for log collection
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    
    # Output to Elasticsearch without security
    config:
      outputs: |
        [OUTPUT]
            Name  es
            Match *
            Host  elasticsearch-master.logging.svc.cluster.local
            Port  9200
            Index fluent-bit
            Logstash_Format On
            Retry_Limit False
