apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/instance: elasticsearch
    app.kubernetes.io/part-of: platform
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: elasticsearch
      version: '8.5.1'
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicas: 1
    minimumMasterNodes: 1
    clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
    esJavaOpts: "-Xmx512m -Xms512m"
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
    # Use official chart defaults: HTTPS with auto-generated certs
    protocol: https
    createCert: true
    secret:
      enabled: true
      password: "changeme"  # Change in production
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kibana
  namespace: logging
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/instance: kibana
    app.kubernetes.io/part-of: platform
spec:
  interval: 10m
  timeout: 10m
  # Wait for Elasticsearch to be ready before installing Kibana
  dependsOn:
    - name: elasticsearch
      namespace: logging
  chart:
    spec:
      chart: kibana
      version: '8.5.1'
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: false
    disableHooks: true
    remediation:
      retries: 3
  upgrade:
    disableHooks: true
    remediation:
      retries: 3
  values:
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
    # Official chart defaults for connecting to Elasticsearch
    elasticsearchHosts: "https://elasticsearch-master:9200"
    elasticsearchCertificateSecret: "elasticsearch-master-certs"
    elasticsearchCertificateAuthoritiesFile: "ca.crt"
    elasticsearchCredentialSecret: "elasticsearch-master-credentials"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/part-of: platform
spec:
  interval: 10m
  chart:
    spec:
      chart: fluent-bit
      version: '0.21.7'
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: false
  values:
    serviceAccount:
      create: true
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    config:
      outputs: |
        [OUTPUT]
            Name  es
            Match *
            Host  elasticsearch-master.logging.svc.cluster.local
            Port  9200
            HTTP_User elastic
            HTTP_Passwd changeme
            Index fluent-bit
            Logstash_Format On
            Retry_Limit False
            tls On
            tls.verify Off
