apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/instance: elasticsearch
    app.kubernetes.io/part-of: platform
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: elasticsearch
      version: '8.5.1'
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicas: 1
    minimumMasterNodes: 1
    clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
    esJavaOpts: "-Xmx512m -Xms512m"
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
    # Enable HTTPS with self-signed certs (best practice)
    protocol: https
    esConfig:
      elasticsearch.yml: |
        xpack.security.enabled: true
        xpack.security.enrollment.enabled: true
        xpack.security.http.ssl.enabled: true
        xpack.security.http.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
        xpack.security.transport.ssl.enabled: true
        xpack.security.transport.ssl.verification_mode: certificate
        xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
        xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
    # Create default users
    secret:
      enabled: true
      password: "changeme"  # Change in production via sealed secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kibana
  namespace: logging
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/instance: kibana
    app.kubernetes.io/part-of: platform
spec:
  interval: 10m
  timeout: 10m
  # Wait for Elasticsearch to be ready before installing Kibana
  dependsOn:
    - name: elasticsearch
      namespace: logging
  chart:
    spec:
      chart: kibana
      version: '8.5.1'
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: false
    disableHooks: true
    remediation:
      retries: 3
  upgrade:
    disableHooks: true
    remediation:
      retries: 3
  values:
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
    # Connect to Elasticsearch with HTTPS
    elasticsearchHosts: "https://elasticsearch-master.logging.svc.cluster.local:9200"
    # Use Elasticsearch credentials
    elasticsearchCredentialSecret: "elasticsearch-master-credentials"
    # Trust the self-signed Elasticsearch certificates
    elasticsearchCertificateSecret: "elasticsearch-master-certs"
    elasticsearchCertificateAuthoritiesFile: "ca.crt"
    # Override environment variables for authentication
    extraEnvs:
      - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
        value: "certificate"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/part-of: platform
spec:
  interval: 10m
  chart:
    spec:
      chart: fluent-bit
      version: '0.21.7'
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: false
  values:
    serviceAccount:
      create: true
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    config:
      outputs: |
        [OUTPUT]
            Name  es
            Match *
            Host  elasticsearch-master.logging.svc.cluster.local
            Port  9200
            HTTP_User elastic
            HTTP_Passwd changeme
            Index fluent-bit
            Logstash_Format On
            Retry_Limit False
            tls On
            tls.verify Off
