# Backstage Developer Portal (SQLite Version for Development)
# Official Documentation: https://backstage.io/docs/deployment/k8s

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backstage
  namespace: backstage
  labels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/part-of: backstage
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: backstage
      version: '1.8.2'
      sourceRef:
        kind: HelmRepository
        name: backstage
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: backstage-values
      valuesKey: values.yaml
      optional: true
  values:
    backstage:
      image:
        repository: backstage/backstage
        tag: latest
      resources:
        requests:
          cpu: 100m    # Optimized for 4-core constraint
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 512Mi
      
      # Environment variables for Backstage configuration
      extraEnvVars:
        - name: NODE_ENV
          value: "development"
        - name: LOG_LEVEL
          value: "info"
        
        # Platform integration
        - name: KUBERNETES_CLUSTER_NAME
          value: "k8s-framework"
        - name: PROMETHEUS_URL
          value: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
        - name: GRAFANA_URL
          value: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local"
    
    # Disable PostgreSQL dependency
    postgresql:
      enabled: false
    
    # Service configuration
    service:
      type: ClusterIP
      port: 7007
      
    # Ingress configuration (we'll use Istio instead)
    ingress:
      enabled: false
      
    # Service monitoring
    serviceMonitor:
      enabled: true