# Backstage Developer Portal (SQLite Version for Development)
# Official Documentation: https://backstage.io/docs/deployment/k8s

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backstage
  namespace: backstage
  labels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/part-of: backstage
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: backstage
      version: '1.8.2'
      sourceRef:
        kind: HelmRepository
        name: backstage
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: backstage-values
      valuesKey: values.yaml
      optional: true
  values:
    # Disable PostgreSQL dependency
    postgresql:
      enabled: false
    
    # Service configuration
    service:
      type: ClusterIP
      port: 7007