# Backstage Developer Portal
# Official Documentation: https://backstage.io/docs/deployment/k8s

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: backstage
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/part-of: backstage
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: postgresql
      version: '15.5.32'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      enablePostgresUser: true
      postgresPassword: "backstage-secret"
      username: "backstage"
      password: "backstage-secret"
      database: "backstage_plugin_catalog"
    primary:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 300m
          memory: 512Mi
      persistence:
        enabled: true
        size: 2Gi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backstage
  namespace: backstage
  labels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/part-of: backstage
spec:
  interval: 10m
  timeout: 15m
  dependsOn:
    - name: postgresql
      namespace: backstage
  chart:
    spec:
      chart: backstage
      version: '1.8.2'
      sourceRef:
        kind: HelmRepository
        name: backstage
        namespace: flux-system
  values:
    backstage:
      image:
        repository: backstage/backstage
        tag: latest
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
      
      # Environment variables for Backstage configuration
      extraEnvVars:
        - name: POSTGRES_HOST
          value: postgresql.backstage.svc.cluster.local
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: backstage
        - name: POSTGRES_PASSWORD
          value: backstage-secret
        - name: POSTGRES_DATABASE
          value: backstage_plugin_catalog
        
        # Platform integration
        - name: KUBERNETES_CLUSTER_NAME
          value: "k8s-framework"
        - name: PROMETHEUS_URL
          value: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
        - name: GRAFANA_URL
          value: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local"
        
        # GitHub integration (adjust as needed)
        - name: GITHUB_TOKEN
          value: "your-github-token-here"
    
    # Service configuration
    service:
      type: ClusterIP
      port: 7007
      
    # Ingress configuration (we'll use Istio instead)
    ingress:
      enabled: false
      
    # Service monitoring
    serviceMonitor:
      enabled: true