apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: logging
  labels:
    app.kubernetes.io/part-of: platform
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
