repositories:
  - name: argo-helm
    url: https://argoproj.github.io/argo-helm
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: elastic
    url: https://helm.elastic.co
  - name: fluent
    url: https://fluent.github.io/helm-charts
  - name: jaegertracing
    url: https://jaegertracing.github.io/helm-charts

helmDefaults:
  wait: true
  timeout: 900

releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    values:
      - values/ingress-nginx-values.yaml
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    values:
      - values/cert-manager-values.yaml
  - name: istiod
    namespace: istio-system
    chart: istio/istiod
    values:
      - values/istio-values.yaml
  - name: istio-ingress
    namespace: istio-system
    chart: istio/gateway
    values:
      - values/istio-values.yaml
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    values:
      - values/prometheus-values.yaml
  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    values:
      - values/grafana-values.yaml
  - name: elasticsearch
    namespace: logging
    chart: elastic/elasticsearch
    values:
      - values/logging-values.yaml
  - name: kibana
    namespace: logging
    chart: elastic/kibana
    values:
      - values/logging-values.yaml
  - name: fluent-bit
    namespace: logging
    chart: fluent/fluent-bit
    values:
      - values/logging-values.yaml
  - name: jaeger
    namespace: tracing
    chart: jaegertracing/jaeger
    installed: true
    values:
      - values/tracing-values.yaml
  - name: argocd
    namespace: argocd
    chart: argo-helm/argo-cd
    installed: false
    values:
      - values/argocd-values.yaml
