apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform:readonly
  labels:
    app.kubernetes.io/part-of: platform
rules:
- apiGroups: ["", "apps", "batch", "extensions"]
  resources: ["pods", "services", "deployments", "daemonsets", "statefulsets", "jobs", "cronjobs", "events", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-readonly
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform:readonly-binding
  labels:
    app.kubernetes.io/part-of: platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform:readonly
subjects:
- kind: ServiceAccount
  name: platform-readonly
  namespace: monitoring
