apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
  labels:
    app.kubernetes.io/name: istio
    app.kubernetes.io/instance: istiod
    app.kubernetes.io/part-of: platform
spec:
  interval: 10m
  chart:
    spec:
      chart: istiod
      version: 1.28.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    meshConfig:
      enablePrometheusMerge: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-system
  labels:
    app.kubernetes.io/name: istio-ingress
    app.kubernetes.io/instance: istio-ingress
    app.kubernetes.io/part-of: platform
spec:
  interval: 10m
  chart:
    spec:
      chart: gateway
      version: 1.28.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    # Fix the image issue by providing proper values
    image:
      repository: istio/proxyv2
      tag: 1.28.0
    service:
      type: LoadBalancer
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
