apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
  labels:
    app.kubernetes.io/name: istio-base
    app.kubernetes.io/instance: istio-base
    app.kubernetes.io/part-of: platform
spec:
  interval: 10m
  chart:
    spec:
      chart: base
      version: 1.28.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    defaultRevision: default
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
  labels:
    app.kubernetes.io/name: istio
    app.kubernetes.io/instance: istiod
    app.kubernetes.io/part-of: platform
spec:
  interval: 10m
  dependsOn:
    - name: istio-base
      namespace: istio-system
  chart:
    spec:
      chart: istiod
      version: 1.28.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    meshConfig:
      enablePrometheusMerge: true
    pilot:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 300m
          memory: 512Mi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-system
  labels:
    app.kubernetes.io/name: istio-ingress
    app.kubernetes.io/instance: istio-ingress
    app.kubernetes.io/part-of: platform
spec:
  interval: 10m
  dependsOn:
    - name: istiod
      namespace: istio-system
  chart:
    spec:
      chart: gateway
      version: 1.28.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    service:
      type: LoadBalancer
    # resources:
    #   requests:
    #     cpu: 50m
    #     memory: 128Mi
    #   limits:
    #     cpu: 200m
    #     memory: 256Mi
