apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/part-of: platform
spec:
  interval: 10m
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    installCRDs: true
    securityContext:
      runAsNonRoot: false
    containerSecurityContext:
      runAsNonRoot: false
    cainjector:
      securityContext:
        runAsNonRoot: false
      containerSecurityContext:
        runAsNonRoot: false
    webhook:
      securityContext:
        runAsNonRoot: false
      containerSecurityContext:
        runAsNonRoot: false
